module.exports = {
    AllMembers: [
        {
            id:0, //this id is used for api call (should be equal to index number)
            name: "Krish Vijayan",
            pfp: "../images/pfp.JPG",
            uwLogo: "../images/uw.png",
            school: "University of Waterloo",
            program: "Mechatronics Engineering",
            hobbies: ["->Basketball","->Hockey", "->Cricket","->Baseball", "->Valorant","->2K21","->Naruto SS", "->Anime", 
                    "->YouTube","->Tv Shows", "->Movies", "->Driving", "->Music"],
            interests: ["->Programming", "->NBA", "->Computers","->Peripherals","->Technology"],
            qr: "../images/qr.jpg",
            link: "https://www.linkedin.com/in/krish-vijayan-617263219",
        },
        {
            id:1,
            name: "Brandon Wang",
            photo: "../images/pfp.JPG",
            school: "../images/school.JPG",
            program: "Honours Mathematics",
            interests: "Anime, Games, Jpop",
            linkedin: "https://www.linkedin.com/in/bw856/",
            github: "https://github.com/bw856",
        },
        {
            id:2,
            name: "Serena Wittenberg",
            pfp: "../images/serena-pfp.jpg",
            uwLogo: "../images/serena-uw.png",
            school: "University of Waterloo",
            program: "Biomedical Engineering",
            hobbies: ["Chess","Swimming", "Programming", "Design"],
            interests: ["Video Editing", "IOS Development", "Piano"],
            qr: "../images/serena-qr.jpg",
            link: "https://www.linkedin.com/in/serena-wittenberg",
        },
        {
            id:3,
            name: "Taeyun Kim",
            pfp: "../images/pfp.JPG",
            uwLogo: "../images/uw.png",
            school: "University of Waterloo",
            program: "Honours Mathematics",
            hobbies: ["-> Gaming","-> Cooking", "-> Swimming","-> Travelling"],
            interests: ["-> Car", "-> Music", "-> E-Sports","-> Stock","-> Technology"],
            qr: "../images/qr.JPG",
            link: "https://www.linkedin.com/in/taeyun-kim-ba18291b7",
        },
    ]
 };